### ISSUE TITLE
Compress the display

### ISSUE THREAD

**Issue by TDMatthews** [alfredxing/moment#2]
Love the addon! I'm using an older laptop at work with a lower resolution and the weather info is slitghtly off screen. Is there a way (maybe through the custom CSS) that I could remove some of the whitespace between the date and the weather?

**Comment by alfredxing** [comment]
What I have in the CSS right now for the weather is this:

``` CSS
.wunderground {
        display: block;
        font-weight: 300;
}
```

Perhaps you can put

``` CSS
.wunderground {
        margin-top: -100px
}
```

in the custom CSS (change -100px to however much you need)?

Tell me if it works :smiley:
